import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const elixirSidebar: SidebarsConfig = {
  elixirSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default elixirSidebar;
