import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const goSidebar: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  goSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  // tutorialSidebar: ["intro", "Go"],
};

export default goSidebar;
