import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const kubernetesSidebar: SidebarsConfig = {
  kubernetesSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default kubernetesSidebar;
