import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const postgresSidebar: SidebarsConfig = {
  postgresSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default postgresSidebar;
