import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const rustSidebar: SidebarsConfig = {
  rustSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default rustSidebar;
